// Auto-generated by build-projects.ps1
// Last updated: 2026-07-11 22:26:41
// To update: add/remove folders and images in /projects, then run build-projects.ps1

const PROJECTS_DATA = [
  {
    "name": "גינת גג - רמת גן",
    "images": [
      "projects/גינת גג - רמת גן/photo1.jpg"
    ]
  },
  {
    "name": "דוגמה - משרדי NAYAX",
    "images": [
      "projects/דוגמה - משרדי NAYAX/01.jpg",
      "projects/דוגמה - משרדי NAYAX/02.jpg"
    ]
  }
];
