// Auto-generated by build-projects.ps1
// Last updated: 2026-07-22 00:27:31
// To update: add/remove folders and images in /projects, then run build-projects.ps1

const PROJECTS_DATA = [
  {
    "name": "Amazon",
    "images": [
      "projects/Amazon/1.jpg",
      "projects/Amazon/2.jpg",
      "projects/Amazon/3.jpg",
      "projects/Amazon/4.jpg",
      "projects/Amazon/5.jpg"
    ]
  },
  {
    "name": "Compugen",
    "images": [
      "projects/Compugen/WhatsApp Image 2016-10-31 at 09.50.49.jpeg",
      "projects/Compugen/WhatsApp Image 2016-10-31 at 09.50.50.jpeg",
      "projects/Compugen/WhatsApp Image 2016-10-31 at 09.50.55.jpeg",
      "projects/Compugen/WhatsApp Image 2016-10-31 at 09.50.56.jpeg"
    ]
  },
  {
    "name": "Hubz",
    "images": [
      "projects/Hubz/DSCN0869.JPG",
      "projects/Hubz/DSCN0870.JPG",
      "projects/Hubz/DSCN0871.JPG",
      "projects/Hubz/DSCN0873_edited.jpg",
      "projects/Hubz/DSCN0874.JPG",
      "projects/Hubz/DSCN0875.JPG",
      "projects/Hubz/DSCN0876.JPG",
      "projects/Hubz/DSCN0877.JPG",
      "projects/Hubz/DSCN0878_edited.jpg"
    ]
  },
  {
    "name": "IronSource",
    "images": [
      "projects/IronSource/_DSC5152 copy.jpg",
      "projects/IronSource/_DSC5168 copy.jpg",
      "projects/IronSource/_DSC5225 copy.jpg",
      "projects/IronSource/_DSC5346 copy.jpg",
      "projects/IronSource/_DSC5348 copy.jpg",
      "projects/IronSource/_DSC5354 copy.jpg",
      "projects/IronSource/_DSC5409 copy.jpg",
      "projects/IronSource/DSCN1115.JPG",
      "projects/IronSource/DSCN1117.JPG",
      "projects/IronSource/DSCN1119.JPG",
      "projects/IronSource/DSCN1120.JPG",
      "projects/IronSource/DSCN1121.JPG",
      "projects/IronSource/DSCN1122.JPG",
      "projects/IronSource/DSCN1123.JPG",
      "projects/IronSource/DSCN1124.JPG",
      "projects/IronSource/DSCN1125.JPG",
      "projects/IronSource/DSCN1126.JPG",
      "projects/IronSource/DSCN1129.JPG",
      "projects/IronSource/DSCN1131.JPG",
      "projects/IronSource/DSCN1134.JPG",
      "projects/IronSource/DSCN1137.JPG",
      "projects/IronSource/DSCN1141.JPG",
      "projects/IronSource/DSCN1142.JPG",
      "projects/IronSource/DSCN1144.JPG",
      "projects/IronSource/DSCN1145.JPG",
      "projects/IronSource/DSCN1154.JPG"
    ]
  },
  {
    "name": "Labs",
    "images": [
      "projects/Labs/IMG-20180116-WA0015.jpg",
      "projects/Labs/IMG-20180116-WA0016.jpg",
      "projects/Labs/IMG-20180116-WA0017.jpg",
      "projects/Labs/IMG-20180116-WA0018.jpg",
      "projects/Labs/IMG-20180116-WA0019.jpg",
      "projects/Labs/IMG-20180116-WA0020.jpg",
      "projects/Labs/IMG-20180116-WA0021.jpg",
      "projects/Labs/IMG-20180116-WA0022.jpg",
      "projects/Labs/IMG-20180116-WA0023.jpg",
      "projects/Labs/LABS_TLV_©__LUZ-22.jpg",
      "projects/Labs/LABS_TLV_©__LUZ-32.jpg",
      "projects/Labs/LABS_TLV_©__LUZ-74.jpg"
    ]
  },
  {
    "name": "Prospera",
    "images": [
      "projects/Prospera/1.jpg",
      "projects/Prospera/IMG_0020 (Large).jpg",
      "projects/Prospera/IMG_0052 (Medium).jpg",
      "projects/Prospera/IMG_0074 (Medium).jpg",
      "projects/Prospera/IMG_0089 (Medium).jpg",
      "projects/Prospera/IMG_0128 (Medium).jpg",
      "projects/Prospera/IMG_0139 (Medium).jpg",
      "projects/Prospera/IMG_0155 (Medium).jpg",
      "projects/Prospera/IMG_0167 (Medium).jpg",
      "projects/Prospera/IMG_0231 (Medium).jpg",
      "projects/Prospera/IMG_0336 (Medium).jpg"
    ]
  },
  {
    "name": "Samsung",
    "images": [
      "projects/Samsung/20180601_152101.jpg",
      "projects/Samsung/20180601_152321.jpg",
      "projects/Samsung/20180601_152334.jpg",
      "projects/Samsung/20180601_152402.jpg",
      "projects/Samsung/20180601_152406.jpg",
      "projects/Samsung/20180601_152411.jpg",
      "projects/Samsung/20180601_152419.jpg",
      "projects/Samsung/20180601_152425.jpg"
    ]
  },
  {
    "name": "TCM",
    "images": [
      "projects/TCM/PHOTO-2019-08-07-13-50-38.jpg",
      "projects/TCM/PHOTO-2019-08-07-13-50-39 (1).jpg",
      "projects/TCM/PHOTO-2019-08-07-13-50-39 (2).jpg",
      "projects/TCM/PHOTO-2019-08-07-13-50-39.jpg",
      "projects/TCM/PHOTO-2019-08-07-13-50-40.jpg"
    ]
  }
];
